version: "3"

tasks:

  proto:
    dir: src
    cmds:
      - buf generate

  mysql:
    cmds:
      - docker run 
          -d 
          --name=mysql 
          -p 4900:4900  
          --env="MYSQL_TCP_PORT=4900" 
          --env="MYSQL_ROOT_PASSWORD=mypassword" 
          mysql

  postgres:
    cmds:
      - docker run
        -d --name postgres
        -e PGDATA=/var/lib/postgresql/data/pgdata
        -e POSTGRES_PASSWORD=postgres
        -p 5432:5432
        postgres

  postgres-schema:
    dotenv:
      - ../config/postgres.env
    dir: src
    cmds:
      - go run . schema

  mysql-schema:
    dotenv:
      - ../config/mysql.env
    dir: src
    cmds:
      - go run . schema

  sqlite-schema:
    dotenv:
      - ../config/sqlite.env
    dir: src
    cmds:
      - go run . schema

  a:
    dotenv: 
      - ../config/postgres.env
      - ../config/a.env
    dir: src
    cmds:
      - task: postgres-schema
      - go run . start

  b:
    dotenv: 
      - ../config/sqlite.env
      - ../config/b.env
    dir: src
    cmds:
      - go run . start

  c:
    dotenv: 
      - ../config/mysql.env
      - ../config/a.env
    dir: src
    cmds:
      - go run . start

  tidy:
    dir: src
    cmds:
      - go mod tidy

  prototest:
    dir: test
    cmds:
      - buf generate
