version: "3"
env:
  run: go run ./cli
tasks:
  ca:
    dir: test_certs
    cmds:
      - openssl genrsa -aes256 -out ca-key.pem 4096
      - openssl req -new -x509 -days 365 -key ca-key.pem -sha256 -out ca.pem

  cert:
    dir: test_certs
    cmds:
      - task: ca
      - openssl genrsa -out client-key.pem 4096
      - openssl req -subj '/CN=localhost' -new -key client-key.pem -out client.csr
      - echo subjectAltName = IP:127.0.0.1,DNS:localhost > extfile.cnf
      - openssl x509 -req -days 365 -sha256 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out client-cert.pem -extfile extfile.cnf

  dev-deps:
    cmds:
      - pip install pre-commit
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest

  precommit:
    cmds:
      - task: proto
      - pre-commit run --all-files

  proto:
    cmds:
      - rm -rf ./grpc
      - buf generate

  mysql:
    cmds:
      - docker run
        -d
        --name=mysql
        -p 4900:4900
        --env="MYSQL_TCP_PORT=4900"
        --env="MYSQL_ROOT_PASSWORD=mypassword"
        mysql

  postgres:
    cmds:
      - docker run
        -d --name postgres
        -e PGDATA=/var/lib/postgresql/data/pgdata
        -e POSTGRES_PASSWORD=postgres
        -p 5432:5432
        postgres

  postgres-schema:
    dotenv:
      - env/postgres.env

    cmds:
      - $run schema

  mysql-schema:
    dotenv:
      - env/mysql.env
    cmds:
      - $run schema

  memory-schema:
    dotenv:
      - env/sqlite.env
    cmds:
      - $run schema

  cluster:
    dotenv:
      - env/tls.env
    cmds:
      - $run cluster start

  health:
    dotenv:
      - env/tls.env
    cmds:
      - $run cluster health
       --address 127.0.0.1:4004  --tls true

  list:
    dotenv:
      - env/tls.env
    cmds:
      - $run cluster describe
       --address 127.0.0.1:9010  --tls true

  postgres-cluster:
    dotenv:
      - env/postgres.env
      - env/a.env
    cmds:
      - task cluster

  memory-cluster:
    dotenv:
      - env/sqlite.env
      - env/b.env
    cmds:
      - task cluster


  mysql-cluster:
    dotenv:
      - env/mysql.env
      - env/a.env
    cmds:
      - task cluster


  tidy:

    cmds:
      - go mod tidy

  prototest:
    dir: test
    cmds:
      - buf generate
